#!/usr/bin/python

from novaclient.v1_1 import client
import ConfigParser, os, sys, base64

NOVA_KEY = '8V4hbEze'

def decode(key, string):
  decoded_chars = []
  string = base64.urlsafe_b64decode(string)
  for i in xrange(len(string)):
    key_c = key[i % len(key)]
    encoded_c = chr(abs(ord(string[i]) - ord(key_c) % 256))
    decoded_chars.append(encoded_c)
  decoded_string = "".join(decoded_chars)
  return decoded_string

nt = None
config = None

try:
  config = ConfigParser.ConfigParser()
  config.readfp(open('/etc/nova/nova.conf'))

  nt = client.Client(
    config.get('keystone_authtoken', 'admin_user'),
    decode(NOVA_KEY, config.get('keystone_authtoken', 'admin_enc_password')),
    config.get('keystone_authtoken', 'admin_tenant_name'),
    '%s://%s:%s/v2.0' % (
      config.get('keystone_authtoken', 'auth_protocol'),
      config.get('keystone_authtoken', 'auth_host'),
      config.get('keystone_authtoken', 'auth_port')
    ),
    service_type='compute')

except (Exception):
  pass

if (not nt or not config):
  sys.exit(0)

host = None

try:
  if (config.has_option('DEFAULT', 'host')):
    host = config.get('DEFAULT', 'host')
  else:
    p = os.popen('hostname')
    host = p.readline().strip()
    p.close()
except(Exception):
  sys.exit(0)

if (host):
  try:
    nt.services.enable(host, 'nova-compute')
  except (Exception):
    pass
