#!/usr/bin/python

from novaclient.v1_1 import client
import ConfigParser, os

config = ConfigParser.ConfigParser()
config.readfp(open('/etc/nova/nova.conf'))

nt = client.Client(
  config.get('keystone_authtoken', 'admin_user'), 
  config.get('keystone_authtoken', 'admin_password'), 
  config.get('keystone_authtoken', 'admin_tenant_name'), 
  '%s://%s:%s/v2.0' % (
    config.get('keystone_authtoken', 'auth_protocol'),
    config.get('keystone_authtoken', 'auth_host'), 
    config.get('keystone_authtoken', 'auth_port')
  ), 
  service_type='compute')

p = os.popen('hostname')
host = p.readline().strip()
p.close()

client.hosts.get(host).startup()
